apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutantdna-deploy
  labels:
    name: mutantdna-deploy
    app: mutantdna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutantdna
      type: app
  template:
    metadata:
      name: mutantdna-pod
      labels:
        app: mutantdna
        type: app
    spec:
      containers:
        - name: mutantdna
          image: wilcor7190/mutantdna:v1.0
          env:
          - name: ENV
            value: mongo-service
          ports:
<<<<<<< HEAD
          - containerPort: 8080
=======
          - containerPort: 9200
>>>>>>> ca2d8ab7d6aff2c94a4ace7b1d88fb8e7a3abd02
