apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pod
  labels:
    app: mongodb
    type: bd
spec:
  containers:
    - name: mongo
      image: mongo:4.0.4
      env:
      - name: AUTH
        value: "no"
      ports:
        - containerPort: 27017
