apiVersion: v1
kind: Pod
metadata:
  name: mutantdna-pod
  labels:
    app: mutantdna
    type: app
spec:
  containers:
    - name: mutantdna
      image: wilcor7190/mutantdna:v1.0
      env:
      - name: ENV
        value: mongo-service
      ports:
      - containerPort: 9200

    
